from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field, field_validator

from app.schemas.user import UserOut


class LoginRequest(BaseModel):
    """
    Login credentials.
    ✅ SECURITY: EmailStr strictly validates format (e.g., rejects "user@domain" without TLD)
    This prevents malformed emails from even reaching the database query.
    """
    email: EmailStr = Field(
        ...,
        description="User email address (must be valid format)"
    )
    
    password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="User password (8-128 characters)"
    )

    @field_validator("email")
    @classmethod
    def normalize_email(cls, v: str) -> str:
        """Normalize email to lowercase to prevent case-sensitivity issues."""
        return v.lower().strip()


class TokenOut(BaseModel):
    """Authentication token response."""
    access_token: str
    refresh_token: str  # ✅ Required for the 7-day rotating refresh token flow
    token_type: str = "bearer"
    user: UserOut


class RefreshRequest(BaseModel):
    """
    Payload for /auth/refresh and /auth/logout endpoints.
    """
    refresh_token: str = Field(
        ..., 
        min_length=32,  # Opaque tokens generated by secrets.token_urlsafe(32) are 43 chars
        max_length=128,
        description="The opaque refresh token to rotate or revoke"
    )


class ForgotPasswordRequest(BaseModel):
    """
    Password reset initiation request.
    ✅ SECURITY: EmailStr ensures only valid email formats trigger the reset flow.
    The router will return a generic response regardless of whether the email exists
    to prevent user enumeration attacks.
    """
    email: EmailStr = Field(
        ...,
        description="Email address associated with the account"
    )

    @field_validator("email")
    @classmethod
    def normalize_email(cls, v: str) -> str:
        """Normalize email to lowercase."""
        return v.lower().strip()


class ResetPasswordRequest(BaseModel):
    """
    Password reset completion request.
    """
    token: str = Field(
        ...,
        min_length=32,
        max_length=256,
        description="The password reset token received via email"
    )
    
    new_password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="New password (8-128 characters)"
    )

    @field_validator("new_password")
    @classmethod
    def validate_password_strength(cls, v: str) -> str:
        """
        ✅ SECURITY: Enforce basic password strength requirements.
        """
        if not any(c.isupper() for c in v):
            raise ValueError("Password must contain at least one uppercase letter")
        if not any(c.islower() for c in v):
            raise ValueError("Password must contain at least one lowercase letter")
        if not any(c.isdigit() for c in v):
            raise ValueError("Password must contain at least one digit")
        return v


class SessionOut(BaseModel):
    """
    Output schema for user session information.
    Used for "Where am I logged in?" UI and session management.
    """
    id: int
    user_id: int
    user_agent: Optional[str] = None
    ip_address: Optional[str] = None
    created_at: datetime
    expires_at: datetime
    revoked: bool
    revoked_at: Optional[datetime] = None
    is_current: bool = False  # ✅ Set by router when comparing with current token

    model_config = {"from_attributes": True}
