# app/schemas/task.py

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from app.models.task import TaskStatus, TaskPriority, TaskCategory


class TaskBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=255, description="Task title (1-255 characters)")
    description: Optional[str] = Field(default=None, max_length=5000, description="Task description (max 5000 characters)")
    category: TaskCategory = Field(..., description="Task category (strict enum validation)")
    priority: TaskPriority = TaskPriority.medium
    due_date: Optional[datetime] = Field(default=None, description="When the task is due")
    target_type: Optional[str] = Field(default=None, max_length=50, description="Polymorphic reference type (e.g., 'booking', 'vehicle')")
    target_id: Optional[int] = Field(default=None, description="Polymorphic reference ID")
    location_id: Optional[int] = Field(default=None, description="Future-proofing: Multi-branch support")


class TaskCreate(TaskBase):
    """
    Input schema for creating a new task.
    ✅ SECURITY: created_by is set server-side from current_user.id (not client input)
    """
    user_id: Optional[int] = Field(default=None, description="Optional: assign to specific user on creation")
    is_system_generated: bool = Field(default=True, description="Whether task was auto-generated by system")
    requires_role: Optional[str] = Field(default=None, max_length=50, description="Role required if task is unassigned")


class TaskUpdate(BaseModel):
    """
    Input schema for updating an existing task.
    All fields optional — only provided fields are updated.
    """
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=5000)
    category: Optional[TaskCategory] = None
    priority: Optional[TaskPriority] = None
    status: Optional[TaskStatus] = Field(default=None, description="Update task status (strict enum validation)")
    user_id: Optional[int] = Field(default=None, description="Reassign task to different user")
    due_date: Optional[datetime] = None
    completed_at: Optional[datetime] = Field(default=None, description="When task was completed (auto-set on status=completed)")


class TaskOut(TaskBase):
    """
    Output schema for task responses.
    Includes tenant_id for multi-tenancy transparency.
    """
    id: int
    tenant_id: int
    user_id: Optional[int] = None
    created_by: Optional[int] = None
    requires_role: Optional[str] = None
    status: TaskStatus
    is_system_generated: bool
    is_archived: bool
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime] = None

    model_config = {"from_attributes": True}
