"""add_client_invites_table

Revision ID: 06b5683658b1
Revises: 2d33874a7e11
Create Date: 2026-08-18 12:06:22.786942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b5683658b1'
down_revision: Union[str, Sequence[str], None] = '2d33874a7e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', name='clientinvitestatus'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accepted_client_id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('client_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_invites_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invites_id'), ['id'], unique=False)
        batch_op.create_index('ix_client_invites_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_client_invites_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_invites', schema=None) as batch_op:
        batch_op.drop_index('ix_client_invites_tenant_status')
        batch_op.drop_index('ix_client_invites_tenant_created')
        batch_op.drop_index(batch_op.f('ix_client_invites_id'))
        batch_op.drop_index(batch_op.f('ix_client_invites_created_by'))

    op.drop_table('client_invites')
    # ### end Alembic commands ###
