"""client_identity_slot_and_uniqueness

Revision ID: 2d33874a7e11
Revises: a222d0fe0451
Create Date: 2026-08-18 10:55:23.610400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d33874a7e11'
down_revision: Union[str, Sequence[str], None] = 'a222d0fe0451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ PROACTIVE: create the PG enum type before add_column references it
    # (op.add_column with sa.Enum does NOT auto-create the type on Postgres)
    sa.Enum('national_id', 'passport', name='idtype').create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type', sa.Enum('national_id', 'passport', name='idtype'), server_default='national_id', nullable=False))
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('flag_notes', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_tenant_id_number'), type_='unique')
        batch_op.create_unique_constraint('uq_tenant_dl_number', ['tenant_id', 'dl_number'])
        batch_op.create_unique_constraint('uq_tenant_email', ['tenant_id', 'email'])
        batch_op.create_unique_constraint('uq_tenant_id_slot', ['tenant_id', 'id_type', 'id_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenant_id_slot', type_='unique')
        batch_op.drop_constraint('uq_tenant_email', type_='unique')
        batch_op.drop_constraint('uq_tenant_dl_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_id_number'), ['tenant_id', 'id_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('flag_notes')
        batch_op.drop_column('is_flagged')
        batch_op.drop_column('id_type')

    # ### end Alembic commands ###

    # ✅ Drop the enum type after the column is gone
    sa.Enum('national_id', 'passport', name='idtype').drop(op.get_bind(), checkfirst=True)
