"""add dl_number to clients

Revision ID: 2e0a6195e9b4
Revises: 0e452b0d4f2b
Create Date: 2026-06-21 11:06:10.079055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0a6195e9b4'
down_revision: Union[str, Sequence[str], None] = '0e452b0d4f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('dl_expiry', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'dl_expiry')
    # ### end Alembic commands ###
