"""add_commission_payments_table

Revision ID: 3595b1a3cffb
Revises: 6aed5114c575
Create Date: 2026-08-17 14:03:04.530632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3595b1a3cffb'
down_revision: Union[str, Sequence[str], None] = '6aed5114c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='commissionpaymentstatus'), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_payments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payments_id'), ['id'], unique=False)
        batch_op.create_index('ix_commission_payments_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_commission_payments_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_payments_tenant_id'))
        batch_op.drop_index('ix_commission_payments_tenant_created')
        batch_op.drop_index('ix_commission_payments_status_created')
        batch_op.drop_index(batch_op.f('ix_commission_payments_id'))
        batch_op.drop_index(batch_op.f('ix_commission_payments_created_by'))

    op.drop_table('commission_payments')
    # ### end Alembic commands ###
