"""add_share_tokens_to_bookings

Revision ID: 4202f496634c
Revises: bd56807a4754
Create Date: 2026-06-29 01:52:18.396799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4202f496634c'
down_revision: Union[str, Sequence[str], None] = 'bd56807a4754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('share_token', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bookings_share_token'), 'bookings', ['share_token'], unique=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.drop_constraint(op.f('invoices_subscription_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_tenant_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_booking_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('invoices', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_booking_id_fkey'), 'invoices', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('invoices_tenant_id_fkey'), 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('invoices_subscription_id_fkey'), 'invoices', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('invoices', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoices', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'KES'::character varying"),
               existing_nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus'),
               server_default=sa.text("'draft'::invoicestatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_bookings_share_token'), table_name='bookings')
    op.drop_column('bookings', 'share_token')
    # ### end Alembic commands ###
