"""harden initial schema

Revision ID: 45990e58dbd1
Revises: 194bb0150c7a
Create Date: 2026-06-04 17:07:11.398132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45990e58dbd1'
down_revision: Union[str, Sequence[str], None] = '194bb0150c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default='KES',
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'active', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               server_default='pending',
               nullable=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False)
    op.drop_constraint(op.f('bookings_tenant_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_vehicle_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_client_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_tenant_id_fkey', 'bookings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_vehicle_id_fkey', 'bookings', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_client_id_fkey', 'bookings', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('clients', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', 'suspended', name='clientstatus'),
               server_default='pending',
               nullable=False)
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(),
               server_default='starter',
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default='tenant_staff',
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', 'retired', name='vehiclestatus'),
               server_default='available',
               nullable=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', 'retired', name='vehiclestatus'),
               server_default=None,
               nullable=True)
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('clients', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', 'suspended', name='clientstatus'),
               server_default=None,
               nullable=True)
    op.drop_constraint('bookings_client_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_vehicle_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_tenant_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_client_id_fkey'), 'bookings', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('bookings_vehicle_id_fkey'), 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('bookings_tenant_id_fkey'), 'bookings', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_bookings_vehicle_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'active', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               server_default=None,
               nullable=True)
    op.alter_column('bookings', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
