"""add archive suspension subscription invoice payment models

Revision ID: 4b5a253fa03a
Revises: 60aefafa53ec
Create Date: 2026-06-05 21:17:55.410318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5a253fa03a'
down_revision: Union[str, Sequence[str], None] = '60aefafa53ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('free_trial', 'starter_trial', 'starter', 'pro', 'enterprise', name='plantype'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('trial', 'monthly', 'annual', name='billingcycle'), nullable=False),
    sa.Column('status', sa.Enum('trial', 'starter_trial', 'active', 'past_due', 'suspended', 'cancelled', name='subscriptionstatus'), server_default='trial', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus'), server_default='draft', nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('method', sa.Enum('mpesa', 'manual', name='paymentmethod'), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='paymentstatus'), server_default='pending', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.add_column('bookings', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bookings', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('clients', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.Enum('trial', 'starter_trial', 'active', 'past_due', 'suspended', 'cancelled', name='subscriptionstatus'), server_default='trial', nullable=False))
    op.add_column('tenants', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(),
               server_default='free_trial',
               existing_nullable=False)
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('suspension_reason', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('vehicles', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'archived_at')
    op.drop_column('vehicles', 'is_archived')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'is_suspended')
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'starter'::character varying"),
               existing_nullable=False)
    op.drop_column('tenants', 'grace_period_ends_at')
    op.drop_column('tenants', 'subscription_ends_at')
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('clients', 'archived_at')
    op.drop_column('clients', 'is_archived')
    op.drop_column('bookings', 'archived_at')
    op.drop_column('bookings', 'is_archived')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
