"""scope_document_numbers_per_tenant

Revision ID: 6aed5114c575
Revises: 7b36a0457c5b
Create Date: 2026-08-17 12:32:35.118224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aed5114c575'
down_revision: Union[str, Sequence[str], None] = '7b36a0457c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_booking_number'))
        batch_op.create_index(batch_op.f('ix_bookings_booking_number'), ['booking_number'], unique=False)
        batch_op.create_unique_constraint('uq_bookings_tenant_booking_number', ['tenant_id', 'booking_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bookings_tenant_booking_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bookings_booking_number'))
        batch_op.create_index(batch_op.f('ix_bookings_booking_number'), ['booking_number'], unique=True)

    # ### end Alembic commands ###
