"""add_commission_events_table

Revision ID: 784706de9974
Revises: 55d80c309c29
Create Date: 2026-08-16 23:55:18.559756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784706de9974'
down_revision: Union[str, Sequence[str], None] = '55d80c309c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'waived', name='commissionstatus'), nullable=False),
    sa.Column('trip_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('commission_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_events_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_commission_tenant_started', ['tenant_id', 'trip_started_at'], unique=False)
        batch_op.create_index('ix_commission_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_events', schema=None) as batch_op:
        batch_op.drop_index('ix_commission_tenant_status')
        batch_op.drop_index('ix_commission_tenant_started')
        batch_op.drop_index(batch_op.f('ix_commission_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_commission_events_id'))
        batch_op.drop_index(batch_op.f('ix_commission_events_created_by'))

    op.drop_table('commission_events')
    # ### end Alembic commands ###
