"""update app/schemas/vehicle.py

Revision ID: 79d1d86e56cb
Revises: ca94d6524482
Create Date: 2026-06-22 14:23:47.922242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d1d86e56cb'
down_revision: Union[str, Sequence[str], None] = 'ca94d6524482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
