"""add vehicle mileage tracking

Revision ID: 7a86d245a1bb
Revises: 2e0a6195e9b4
Create Date: 2026-06-21 21:20:18.001312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a86d245a1bb'
down_revision: Union[str, Sequence[str], None] = '2e0a6195e9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_mileage', sa.Integer(), server_default='0', nullable=False))
    op.add_column('vehicles', sa.Column('next_service_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'next_service_km')
    op.drop_column('vehicles', 'current_mileage')
    # ### end Alembic commands ###
