"""add_platform_settings_singleton

Revision ID: 7b36a0457c5b
Revises: 784706de9974
Create Date: 2026-08-17 01:18:22.050618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36a0457c5b'
down_revision: Union[str, Sequence[str], None] = '784706de9974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), server_default='150.00', nullable=False),
    sa.Column('grace_period_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('platform_paybill', sa.String(length=50), nullable=True),
    sa.Column('platform_account_name', sa.String(length=150), nullable=True),
    sa.Column('platform_phone', sa.String(length=20), nullable=True),
    sa.Column('platform_email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_platform_settings_singleton'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_settings_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_settings_created_by'))

    op.drop_table('platform_settings')
    # ### end Alembic commands ###
