"""add_expected_client_to_invites

Revision ID: 83e48de291c1
Revises: 06b5683658b1
Create Date: 2026-08-18 15:23:29.351046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e48de291c1'
down_revision: Union[str, Sequence[str], None] = '06b5683658b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expected_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_invites', schema=None) as batch_op:
        batch_op.drop_column('expected_phone')
        batch_op.drop_column('expected_name')

    # ### end Alembic commands ###
