"""add driver fee stack to service pricing configs

Revision ID: 843709a296eb
Revises: fec0bf877acb
Create Date: 2026-08-21 12:58:58.892277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843709a296eb'
down_revision: Union[str, Sequence[str], None] = 'fec0bf877acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pricing_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_daily_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('driver_overtime_hourly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('driver_night_accommodation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
                # ✅ MANUAL: autogenerate can't detect check constraints on existing tables
        batch_op.create_check_constraint("ck_pricing_driver_daily_fee_non_negative",
            condition="driver_daily_fee IS NULL OR driver_daily_fee >= 0")
        batch_op.create_check_constraint("ck_pricing_driver_ot_fee_non_negative",
            condition="driver_overtime_hourly_fee IS NULL OR driver_overtime_hourly_fee >= 0")
        batch_op.create_check_constraint("ck_pricing_driver_accommodation_non_negative",
            condition="driver_night_accommodation_fee IS NULL OR driver_night_accommodation_fee >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pricing_configs', schema=None) as batch_op:
        # ✅ Constraints MUST be dropped before the columns they reference
        batch_op.drop_constraint("ck_pricing_driver_accommodation_non_negative", type_="check")
        batch_op.drop_constraint("ck_pricing_driver_ot_fee_non_negative", type_="check")
        batch_op.drop_constraint("ck_pricing_driver_daily_fee_non_negative", type_="check")
        batch_op.drop_column('driver_night_accommodation_fee')
        batch_op.drop_column('driver_overtime_hourly_fee')
        batch_op.drop_column('driver_daily_fee')
    # ### end Alembic commands ###
