"""Add contract sharing tokens and client signature fields

Revision ID: ca94d6524482
Revises: 07fee01dee8a
Create Date: 2026-06-22 13:54:51.345023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca94d6524482'
down_revision: Union[str, Sequence[str], None] = '07fee01dee8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('share_token', sa.String(length=36), nullable=True))
    op.add_column('contracts', sa.Column('share_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contracts', sa.Column('signed_by_client', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contracts', sa.Column('client_signed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_contracts_share_token'), 'contracts', ['share_token'], unique=True)
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_constraint(op.f('invoices_booking_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'booking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invoices_booking_id_fkey'), 'invoices', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_contracts_share_token'), table_name='contracts')
    op.drop_column('contracts', 'client_signed_at')
    op.drop_column('contracts', 'signed_by_client')
    op.drop_column('contracts', 'share_token_expires_at')
    op.drop_column('contracts', 'share_token')
    # ### end Alembic commands ###
