"""add share_token_expires_at to bookings

Revision ID: cc8f0fabbb25
Revises: 4202f496634c
Create Date: 2026-06-29 02:47:20.328618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8f0fabbb25'
down_revision: Union[str, Sequence[str], None] = '4202f496634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('share_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'share_token_expires_at')
    # ### end Alembic commands ###
