"""add_task_status_and_category_enums

Revision ID: d7c7fb8fe084
Revises: f9fc4b1cfe94
Create Date: 2026-07-29 19:19:05.530624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c7fb8fe084'
down_revision: Union[str, Sequence[str], None] = 'f9fc4b1cfe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ MANUALLY ADDED: Add new values to the existing 'taskstatus' enum in PostgreSQL
    op.execute("ALTER TYPE taskstatus ADD VALUE 'in_progress'")
    op.execute("ALTER TYPE taskstatus ADD VALUE 'in_review'")
    op.execute("ALTER TYPE taskstatus ADD VALUE 'blocked'")

    op.create_index('ix_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_airtel_configs_tenant_active', 'airtel_money_configs', ['tenant_id', 'is_active'], unique=False)
    op.drop_constraint(op.f('bank_account_configs_tenant_id_key'), 'bank_account_configs', type_='unique')
    op.create_index(op.f('ix_bank_account_configs_tenant_id'), 'bank_account_configs', ['tenant_id'], unique=False)
    op.create_index('ix_bank_configs_tenant', 'bank_account_configs', ['tenant_id'], unique=False)
    op.create_index('ix_bank_configs_tenant_id', 'bank_account_configs', ['tenant_id', 'id'], unique=False)
    op.create_index('ix_bank_configs_tenant_primary', 'bank_account_configs', ['tenant_id', 'is_primary'], unique=False)
    op.create_index('ix_bookings_tenant_archived', 'bookings', ['tenant_id', 'is_archived', 'created_at'], unique=False)
    op.create_index('ix_bookings_tenant_created', 'bookings', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_bookings_tenant_dates', 'bookings', ['tenant_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_bookings_tenant_status_created', 'bookings', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_bookings_vehicle_utilization', 'bookings', ['tenant_id', 'vehicle_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_clients_tenant_archived_created', 'clients', ['tenant_id', 'is_archived', 'created_at'], unique=False)
    op.create_index('ix_clients_tenant_archived_date', 'clients', ['tenant_id', 'is_archived', 'archived_at'], unique=False)
    op.create_index('ix_clients_tenant_status', 'clients', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_contracts_tenant_created', 'contracts', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_contracts_tenant_signed', 'contracts', ['tenant_id', 'status', 'client_signed_at'], unique=False)
    op.create_index('ix_contracts_tenant_status', 'contracts', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_contracts_token_expires', 'contracts', ['share_token', 'share_token_expires_at'], unique=False)
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.create_index('ix_invoices_tenant_id', 'invoices', ['tenant_id', 'id'], unique=False)
    op.create_index('ix_invoices_booking', 'invoices', ['booking_id'], unique=False)
    op.create_index('ix_invoices_tenant_overdue', 'invoices', ['tenant_id', 'status', 'due_date'], unique=False)
    op.create_index('ix_invoices_tenant_paid', 'invoices', ['tenant_id', 'status', 'paid_at'], unique=False)
    op.create_index('ix_invoices_tenant_status_created', 'invoices', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_invoices_token_expires', 'invoices', ['share_token', 'share_token_expires_at'], unique=False)
    op.create_index('ix_mpesa_configs_tenant_active', 'mpesa_configs', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_reset_tokens_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('ix_reset_tokens_user_unused', 'password_reset_tokens', ['user_id', 'used_at', 'created_at'], unique=False)
    op.create_index('ix_reset_tokens_validation', 'password_reset_tokens', ['token_hash', 'expires_at', 'used_at'], unique=False)
    op.create_index('ix_verifications_id', 'payment_verifications', ['id'], unique=False)
    op.create_index('ix_verifications_reference', 'payment_verifications', ['reference_code'], unique=False)
    op.create_index('ix_verifications_status_created', 'payment_verifications', ['status', 'created_at'], unique=False)
    op.create_index('ix_verifications_tenant_status_created', 'payment_verifications', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_tenant_completed', 'payments', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_payments_tenant_paid_at', 'payments', ['tenant_id', 'status', 'paid_at'], unique=False)
    op.create_index('ix_payments_tenant_status_created', 'payments', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_paypal_configs_tenant_active', 'paypal_configs', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_role_templates_tenant_job_title', 'role_templates', ['tenant_id', 'job_title'], unique=False)
    op.create_index('ix_stripe_configs_tenant_active', 'stripe_configs', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_subscriptions_pending_verification', 'subscriptions', ['status', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_status_created', 'subscriptions', ['status', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_status_ends_at', 'subscriptions', ['status', 'ends_at'], unique=False)
    op.create_index('ix_subscriptions_tenant_created', 'subscriptions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_subscriptions_tenant_status', 'subscriptions', ['tenant_id', 'status'], unique=False)
    
    # ✅ FIX: Added postgresql_using to safely cast existing VARCHAR data to the new ENUM type
    op.alter_column('tasks', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('fleet', 'finance', 'hr', 'booking', 'compliance', 'maintenance', 'operations', 'other', name='taskcategory'),
               existing_nullable=False,
               postgresql_using="category::taskcategory")
               
    op.create_index('ix_policies_tenant_active', 'tenant_policies', ['tenant_id', 'is_active', 'display_order'], unique=False)
    op.create_index('ix_policies_tenant_display_order', 'tenant_policies', ['tenant_id', 'display_order'], unique=False)
    op.create_index('ix_policies_tenant_id', 'tenant_policies', ['tenant_id', 'id'], unique=False)
    op.create_index('ix_policies_tenant_section', 'tenant_policies', ['tenant_id', 'section'], unique=False)
    op.drop_index(op.f('ix_tenant_profiles_search'), table_name='tenant_profiles')
    op.create_index('ix_tenant_profiles_tenant_tax', 'tenant_profiles', ['tenant_id', 'tax_number'], unique=False)
    op.drop_index(op.f('ix_tenants_search_vault'), table_name='tenants')
    op.create_index('ix_tenants_active_list', 'tenants', ['is_archived', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_tenants_subscription_expiry', 'tenants', ['subscription_status', 'subscription_ends_at'], unique=False)
    op.create_index('ix_tenants_subscription_status', 'tenants', ['subscription_status', 'is_archived'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_last_login', 'users', ['tenant_id', 'last_login_at'], unique=False)
    op.create_index('ix_users_tenant_role_created', 'users', ['tenant_id', 'role', 'created_at'], unique=False)
    op.create_index('ix_users_tenant_status_created', 'users', ['tenant_id', 'is_active', 'is_suspended', 'created_at'], unique=False)
    op.create_index('ix_vehicles_tenant_archived_created', 'vehicles', ['tenant_id', 'is_archived', 'created_at'], unique=False)
    op.create_index('ix_vehicles_tenant_archived_date', 'vehicles', ['tenant_id', 'is_archived', 'archived_at'], unique=False)
    op.create_index('ix_vehicles_tenant_insurance_expiry', 'vehicles', ['tenant_id', 'insurance_expiry'], unique=False)
    op.create_index('ix_vehicles_tenant_status', 'vehicles', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_tenant_status', table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_insurance_expiry', table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_archived_date', table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_archived_created', table_name='vehicles')
    op.drop_index('ix_users_tenant_status_created', table_name='users')
    op.drop_index('ix_users_tenant_role_created', table_name='users')
    op.drop_index('ix_users_tenant_last_login', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_tenants_subscription_status', table_name='tenants')
    op.drop_index('ix_tenants_subscription_expiry', table_name='tenants')
    op.drop_index('ix_tenants_active_list', table_name='tenants')
    op.create_index(op.f('ix_tenants_search_vault'), 'tenants', ['is_archived', 'name'], unique=False)
    op.drop_index('ix_tenant_profiles_tenant_tax', table_name='tenant_profiles')
    op.create_index(op.f('ix_tenant_profiles_search'), 'tenant_profiles', ['company_name', 'tax_number'], unique=False)
    op.drop_index('ix_policies_tenant_section', table_name='tenant_policies')
    op.drop_index('ix_policies_tenant_id', table_name='tenant_policies')
    op.drop_index('ix_policies_tenant_display_order', table_name='tenant_policies')
    op.drop_index('ix_policies_tenant_active', table_name='tenant_policies')
    
    # ✅ FIX: Revert the cast in downgrade as well for symmetry
    op.alter_column('tasks', 'category',
               existing_type=sa.Enum('fleet', 'finance', 'hr', 'booking', 'compliance', 'maintenance', 'operations', 'other', name='taskcategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="category::varchar")
               
    op.drop_index('ix_subscriptions_tenant_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_tenant_created', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status_ends_at', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status_created', table_name='subscriptions')
    op.drop_index('ix_subscriptions_pending_verification', table_name='subscriptions')
    op.drop_index('ix_stripe_configs_tenant_active', table_name='stripe_configs')
    op.drop_index('ix_role_templates_tenant_job_title', table_name='role_templates')
    op.drop_index('ix_paypal_configs_tenant_active', table_name='paypal_configs')
    op.drop_index('ix_payments_tenant_status_created', table_name='payments')
    op.drop_index('ix_payments_tenant_paid_at', table_name='payments')
    op.drop_index('ix_payments_tenant_completed', table_name='payments')
    op.drop_index('ix_payments_invoice', table_name='payments')
    op.drop_index('ix_verifications_tenant_status_created', table_name='payment_verifications')
    op.drop_index('ix_verifications_status_created', table_name='payment_verifications')
    op.drop_index('ix_verifications_reference', table_name='payment_verifications')
    op.drop_index('ix_verifications_id', table_name='payment_verifications')
    op.drop_index('ix_reset_tokens_validation', table_name='password_reset_tokens')
    op.drop_index('ix_reset_tokens_user_unused', table_name='password_reset_tokens')
    op.drop_index('ix_reset_tokens_expires', table_name='password_reset_tokens')
    op.drop_index('ix_mpesa_configs_tenant_active', table_name='mpesa_configs')
    op.drop_index('ix_invoices_token_expires', table_name='invoices')
    op.drop_index('ix_invoices_tenant_status_created', table_name='invoices')
    op.drop_index('ix_invoices_tenant_paid', table_name='invoices')
    op.drop_index('ix_invoices_tenant_overdue', table_name='invoices')
    op.drop_index('ix_invoices_booking', table_name='invoices')
    op.drop_index('ix_invoices_tenant_id', table_name='invoices')
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.drop_index('ix_contracts_token_expires', table_name='contracts')
    op.drop_index('ix_contracts_tenant_status', table_name='contracts')
    op.drop_index('ix_contracts_tenant_signed', table_name='contracts')
    op.drop_index('ix_contracts_tenant_created', table_name='contracts')
    op.drop_index('ix_clients_tenant_status', table_name='clients')
    op.drop_index('ix_clients_tenant_archived_date', table_name='clients')
    op.drop_index('ix_clients_tenant_archived_created', table_name='clients')
    op.drop_index('ix_bookings_vehicle_utilization', table_name='bookings')
    op.drop_index('ix_bookings_tenant_status_created', table_name='bookings')
    op.drop_index('ix_bookings_tenant_dates', table_name='bookings')
    op.drop_index('ix_bookings_tenant_created', table_name='bookings')
    op.drop_index('ix_bookings_tenant_archived', table_name='bookings')
    op.drop_index('ix_bank_configs_tenant_primary', table_name='bank_account_configs')
    op.drop_index('ix_bank_configs_tenant_id', table_name='bank_account_configs')
    op.drop_index('ix_bank_configs_tenant', table_name='bank_account_configs')
    op.drop_index(op.f('ix_bank_account_configs_tenant_id'), table_name='bank_account_configs')
    op.create_unique_constraint(op.f('bank_account_configs_tenant_id_key'), 'bank_account_configs', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_airtel_configs_tenant_active', table_name='airtel_money_configs')
    op.drop_index('ix_activity_logs_user_created', table_name='activity_logs')
    # ### end Alembic commands ###
