"""add_platform_account_number

Revision ID: d8f898a77f5b
Revises: 3595b1a3cffb
Create Date: 2026-08-17 15:59:43.333460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f898a77f5b'
down_revision: Union[str, Sequence[str], None] = '3595b1a3cffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_account_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_column('platform_account_number')

    # ### end Alembic commands ###
