"""add service pricing config and time-aware booking fields

Revision ID: fec0bf877acb
Revises: 83e48de291c1
Create Date: 2026-08-21 11:53:11.683717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec0bf877acb'
down_revision: Union[str, Sequence[str], None] = '83e48de291c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. STRICTLY ADDITIVE — no drops, no alters, no data loss."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pricing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('day_hours', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_cap_at_day_rate', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('day_hours > 0', name='ck_pricing_day_hours_positive'),
    sa.CheckConstraint('grace_minutes >= 0', name='ck_pricing_grace_non_negative'),
    sa.CheckConstraint('overtime_hourly_rate IS NULL OR overtime_hourly_rate >= 0', name='ck_pricing_overtime_rate_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'service_type', name='uq_pricing_tenant_service_type')
    )
    with op.batch_alter_table('service_pricing_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_pricing_configs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_pricing_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_pricing_configs_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=30), server_default='selfdrive', nullable=False))
        batch_op.add_column(sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scheduled_return_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('actual_return_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pricing_day_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pricing_grace_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pricing_overtime_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_service_type'), ['service_type'], unique=False)

        # ✅ MANUAL: autogenerate cannot detect check constraints on existing tables
        batch_op.create_check_constraint(
            "ck_bookings_valid_schedule",
            condition="scheduled_return_at IS NULL OR pickup_at IS NULL OR scheduled_return_at > pickup_at",
        )
    # ### end Alembic commands ###

    # ✅ SAFE BACKFILL: give legacy rows a time-aware schedule.
    # Idempotent (only touches NULL rows) and copies already-validated dates
    # (end_date > start_date is enforced by ck_bookings_valid_date_range),
    # so the new ck_bookings_valid_schedule is satisfied by construction.
    op.execute("""
        UPDATE bookings
        SET pickup_at = start_date,
            scheduled_return_at = end_date
        WHERE pickup_at IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema. Exact reverse of upgrade."""
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint("ck_bookings_valid_schedule", type_="check")
        batch_op.drop_index(batch_op.f('ix_bookings_service_type'))
        batch_op.drop_column('pricing_overtime_hourly_rate')
        batch_op.drop_column('pricing_grace_minutes')
        batch_op.drop_column('pricing_day_hours')
        batch_op.drop_column('actual_return_at')
        batch_op.drop_column('scheduled_return_at')
        batch_op.drop_column('pickup_at')
        batch_op.drop_column('service_type')

    with op.batch_alter_table('service_pricing_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_pricing_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_pricing_configs_id'))
        batch_op.drop_index(batch_op.f('ix_service_pricing_configs_created_by'))

    op.drop_table('service_pricing_configs')
