# app/models/client_invite.py
import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Column, DateTime, Enum, ForeignKey, Integer, String, Index,
)
from sqlalchemy.orm import relationship

from app.db.database import Base, AuditMixin


class ClientInviteStatus(str, enum.Enum):
    pending = "pending"    # link is live, awaiting first submission
    accepted = "accepted"  # single-use consumed
    revoked = "revoked"    # tenant killed the link


class ClientInvite(Base, AuditMixin):
    """
    ✅ SINGLE-USE, expiring client onboarding invite.

    - `token` is the shareable secret (generated by the service layer).
    - Expiry is COMPUTED (expires_at vs now) — no cleanup job required.
    - `accepted_client_id` is unique → one invite can produce at most ONE client.
    - `expected_name` / `expected_phone` are OPTIONAL and informational only:
      they tell the tenant WHO they're expecting. Never enforced at intake.
    - created_by comes free from AuditMixin (which staff user sent the invite).
    """
    __tablename__ = "client_invites"

    id = Column(Integer, primary_key=True, index=True)
    tenant_id = Column(
        Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )

    # The shareable secret (secrets.token_urlsafe(32) → 43 chars)
    token = Column(String(64), nullable=False, unique=True)

    status = Column(
        Enum(ClientInviteStatus),
        nullable=False,
        default=ClientInviteStatus.pending,
        server_default=ClientInviteStatus.pending.value,
    )

    # Hard deadline for the link (service sets now + ttl_days)
    expires_at = Column(DateTime(timezone=True), nullable=False)

    # ✅ EXPECTED CLIENT (optional, informational): who the tenant is inviting
    expected_name = Column(String(255), nullable=True)
    expected_phone = Column(String(50), nullable=True)

    # The client this invite onboarded (SET NULL if client later deleted)
    accepted_client_id = Column(
        Integer, ForeignKey("clients.id", ondelete="SET NULL"),
        nullable=True, unique=True,
    )

    tenant = relationship("Tenant", backref="client_invites")
    accepted_client = relationship("Client", foreign_keys=[accepted_client_id])

    __table_args__ = (
        # Tenant's invite list with status chips
        Index("ix_client_invites_tenant_status", "tenant_id", "status"),
        # Tenant's invite list ordering
        Index("ix_client_invites_tenant_created", "tenant_id", "created_at"),
    )

    # ── Read-time helpers (no jobs needed) ─────────────────────────
    @property
    def is_expired(self) -> bool:
        return (
            self.status == ClientInviteStatus.pending
            and self.expires_at < datetime.now(timezone.utc)
        )

    @property
    def is_live(self) -> bool:
        return self.status == ClientInviteStatus.pending and not self.is_expired
